import type { Product } from '@/lib/types';

export const productsToSeed: Product[] = [
  {
    id: 'midea-ag11a-07hrdn8i',
    title: 'кондиционер MIDEA AG11A-07HRDN8I / MOX11A-07HFN8I Уценка',
    brand: 'MIDEA',
    description: 'Уцененный товар. Отличная производительность по сниженной цене.',
    price_pmr: 4339,
    old_price_pmr: 6199,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/167/a291079e2c4ae79d677df98f62c0e86b.jpg'],
    specs: {
      'inverter': 'Да',
      'power_btu': 7000,
      'area_sq_m': 20,
      'cooling_power_w': 3220,
      'heating_power_w': 3370,
      'energy_class': 'A++',
      'noise_indoor_db': 24,
      'refrigerant': 'R32',
      'wifi_optional': 'Да'
    },
    category: 'cond',
    stockStatus: true,
  },
  {
    id: 'one-air-oact-09hn8',
    title: 'кондиционер ONE AIR OACT-09HN8',
    brand: 'ONE AIR',
    description: 'Доступный и надежный кондиционер типа ON/OFF. Отлично подходит для дачи и небольших помещений.',
    price_pmr: 3199,
    old_price_pmr: 4349,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/162/a949b251147a752251a31d999086111f.jpg'],
    specs: {
      'inverter': 'Нет',
      'power_btu': 9000,
      'area_sq_m': 25,
      'cooling_power_w': 2491,
      'heating_power_w': 2638,
      'energy_class': 'А',
      'noise_indoor_db': 25,
      'refrigerant': 'R32',
      'features': 'Eco, Fan, Health, I Feel, Mute, Sleep, Turbo'
    },
    category: 'cond',
    stockStatus: true,
  },
  {
    id: 'heinner-hac-hs12wh',
    title: 'кондиционер HEINNER HAC-HS12WH++',
    brand: 'HEINNER',
    description: 'Энергоэффективный инверторный кондиционер для помещений до 35 кв.м.',
    price_pmr: 4799,
    old_price_pmr: 6499,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/163/77197022e37452a3262d0590a2a49b6b.jpg'],
    specs: {
      'inverter': 'Да',
      'power_btu': 12000,
      'area_sq_m': 35,
      'cooling_power_w': 3400,
      'heating_power_w': 2700,
      'energy_class': 'A++',
      'noise_indoor_db': 56,
      'refrigerant': 'R32'
    },
    category: 'cond',
    stockStatus: true,
  },
  {
    id: 'midea-ag11a-09hrdn8i-bk',
    title: 'кондиционер MIDEA AG11A-09HRDN8I-BK',
    brand: 'MIDEA',
    description: 'Стильный и мощный инверторный кондиционер в черном цвете. Высочайший класс энергоэффективности A+++.',
    price_pmr: 5199,
    old_price_pmr: 6999,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/175/7b58c55761eb82d45c6a1e5052ad416f.jpg'],
    specs: {
      'inverter': 'Да',
      'power_btu': 9000,
      'area_sq_m': 25,
      'cooling_power_w': 2780,
      'heating_power_w': 3220,
      'energy_class': 'А+++',
      'noise_indoor_db': 23,
      'refrigerant': 'R32'
    },
    category: 'cond',
    stockStatus: true,
  },
  {
    id: 'ballu-bsyi-10hn8-v4',
    title: 'кондиционер Ballu BSYI-10HN8_V4',
    brand: 'Ballu',
    description: 'Очень тихий инверторный кондиционер (всего 21 дБ). Идеален для спальни.',
    price_pmr: 4292,
    old_price_pmr: 5749,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/164/59a6857187c71e847c5d01a357b98d36.jpg'],
    specs: {
      'inverter': 'Да',
      'power_btu': 10000,
      'area_sq_m': 30,
      'cooling_power_w': 3224,
      'heating_power_w': 3751,
      'energy_class': 'А',
      'noise_indoor_db': 21,
      'refrigerant': 'R32',
      'features': 'Sleep, Автоматическая очистка, Турбо-режим'
    },
    category: 'cond',
    stockStatus: true,
  },
  {
    id: 'gree-inverter-9000-btu-x',
    title: 'кондиционер GREE (Инвертор) 9000 BTU',
    brand: 'GREE',
    description: 'Надежный инверторный кондиционер от лидера рынка GREE. Готов к работе в суровые зимы (до -25°С) благодаря подогреву поддона.',
    price_pmr: 5999,
    old_price_pmr: null,
    price_md: null,
    old_price_md: null,
    images: ['https://hi-tech.md/images/thumbnails/800/800/detailed/172/2920272b1584c5a93945a05b38fcc50f.jpg'],
    specs: {
      'inverter': 'Да',
      'power_btu': 9000,
      'area_sq_m': 25,
      'cooling_power_w': 2500,
      'heating_power_w': 3000,
      'energy_class': 'A++',
      'noise_indoor_db': 25,
      'refrigerant': 'R32',
      'features': 'Подогрев поддона, Wi-Fi'
    },
    category: 'cond',
    stockStatus: true,
  }
];
